name: isds-system

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # Pulls variables directly from your backend .env file
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - isds-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - isds-network

networks:
  isds-network:
    driver: bridge